### ISSUE TITLE
Load put and call contracts dynamically from OptionsFactory

### ISSUE THREAD

**Issue by gonchs** [antoncoding/opyn-monitor#9]
Aside from the additional work, is there any reason why aren't [puts](https://github.com/antoncoding/opyn-monitor/blob/master/src/constants/options/puts.ts) and [calls](https://github.com/antoncoding/opyn-monitor/blob/9fb47bcd4fbd9ed4e229a2e3b86b63d2e864cbb5/src/constants/options/calls.ts) loaded dynamically from the [OptionsFactory](https://etherscan.io/address/0xcc5d905b9c2c8c9329eb4e25dc086369d6c7777c)?

`OptionsFactory` can be iterated to get all contracts and all put/call attributes could be derived from those contracts.

By loading them dynamically, opynmonitor.xyz could allow people to transact with all contracts ever created on the protocol and not select few. This would make opynmonitor.xyz the same what uniswapdex.com (shows all tokens and not just whitelisted) is to uniswap.exchange

**Comment by antoncoding** [comment]
Ahh This is a great idea, I originally hardcoded all the options because of the request limitation from Infura, it would cost too much to query these constants every time. 
Now it seems like we have all the information we need from the opyn subgraph so I guess this would no longer be an issue.

Another potential problem would be having too many options on the list (probably because more and more people are gonna create their own options for testing purpose). I'm thinking about having an optional filter to filter out all the contracts that's not from the opyn tean (contract.owner). Do you have any other suggestions on this?

**Comment by gonchs** [comment]
Hiding all options made by anyone but the team opens removes the ability for more use cases. For example, I would love to write my own puts at specified strike prices and dates. Not for testing purposes but for someone to buy them. Even though the contract allows me to do that, nobody will ever discover them if they are not visible in some interface. And since these put contracts share the exact same code and their only difference is that I'm not on the team of Opyn, it would be against one of the principles of being blockchains and **De**Fi of being permissionless.

We could hide the empty or small option contracts in a similar way in which https://uniswapdex.com/ hides small exchange contracts. By showing some switch or customizable input to filter out contracts with have less than N amount of collateral on them.

![uniswapdex](https://p191.p3.n0.cdn.getcloudapp.com/items/lluD7xAm/Screen%20Shot%202020-05-11%20at%207.48.44%20AM.png?v=aaeca9268c2fb6f8d0f271a96a1a80ea)

To reduce the Infura calls, we could batch RPC calls by using https://github.com/pooltogether/etherplex or https://github.com/makerdao/multicall.js which both use https://github.com/makerdao/multicall

Or also by caching loaded options locally with IndexedDB along with the highest number (count) of the latest loaded option. Then compare the count of options stored locally vs the count in the factory and load only new options.

Further RPC call reduction could be done by only loading N number of latest options and showing "load more" button.

**Comment by antoncoding** [comment]
Yeah I'm not saying I don't want to show other custom options, just want to make sure we have proper filters for users to use so they won't get annoyed.

I think another problem this leads to is where to exchange those newly created options? Currently most people use Uniswap, I think we may need 0x if we want to bootstrap custom options. I have an 0x trading page here:
https://opynmonitor.xyz/#/trade/oeth-usdc
Any idea how to guide users to use it more intuitively?
